### ISSUE TITLE
Support for Django 2.0 ?

### ISSUE THREAD

**Issue by synlord** [justinmayer/django-autoslug#35] opened 2017-12-12 16:35 UTC
Hi,

i have the problem when upgrade to Django 2.0

`from django.core.urlresolvers import get_callable`
`ImportError: No module named 'django.core.urlresolvers'`

**Comment by benmurden** [comment] 2017-12-13 06:22
Have you tried the latest commit? It's not up on PyPi, and there are currently problems getting it there (#31 ), but that may help.

**Comment by barseghyanartur** [comment] 2017-12-20 21:27
I can confirm that it doesn't work with Django 2.0.

**Comment by dhaynespls** [comment] 2017-12-21 14:01
A number of people have submitted PRs for this issue, I'd suggest using one of their forks as I'm not sure the author is currently maintaining the repo. 

https://github.com/neithere/django-autoslug/pull/34

https://github.com/neithere/django-autoslug/pull/33

https://github.com/neithere/django-autoslug/pull/30

**Comment by barseghyanartur** [comment] 2017-12-24 22:21
I switched to ``django-autoslug-iplweb`` ([PyPI](https://pypi.python.org/pypi/django-autoslug-iplweb), [GitHub](https://github.com/iplweb/django-autoslug-iplweb)), which works fine for Django verisons >=1.8,<=2.0.

**Comment by marfyl** [comment] 2018-03-08 13:04
Here you have the original django-autoslug package adapted to django 2

https://github.com/marfyl/django-autoslug

**Comment by barseghyanartur** [comment] 2018-03-08 13:27
@marfyl:

Why fix it in your own fork if the work has been done already (``django-autoslug-iplweb``)?

**Comment by neithere** [comment] 2018-04-23 16:40
FYI, I've found some time to finalize the transfer of the repo to jazzband, so hopefully the project will be resurrected soon. Sorry for the delay.

**Comment by justinmayer** [comment] 2018-07-13 16:43
Apologies for the delay, folks. Django 2.x support has been merged via https://github.com/justinmayer/django-autoslug/commit/4dc75083d84265e019a900d636273c731457193d.

**Closed by justinmayer** 2018-07-13 16:43 UTC

**Comment by moas** [comment] 2018-11-27 00:48
Hallo,

Version 1.9.3 does not supported django 2.0

**Comment by benmurden** [comment] 2018-11-27 01:20
@moas The release on PyPi is delayed due to #49.
